apiVersion: v2
type: application
name: logging-operator-logging
version: 4.2.0
kubeVersion: ">=1.22"
description: A Helm chart to configure logging resource for the Logging operator.
keywords:
  - logging
  - fluentd
  - fluentbit
home: https://kube-logging.github.io
sources:
  - https://github.com/kube-logging/logging-operator
  - https://github.com/kube-logging/helm-charts/tree/main/charts/logging-operator-logging
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Moved to to location
  artifacthub.io/images: |
    - name: fluent-bit
      image: fluent/fluent-bit:2.1.4
    - name: fluentd
      image: ghcr.io/kube-logging/fluentd:v1.15-ruby3
    - name: syslog-ng
      image: ghcr.io/axoflow/axosyslog:4.2.0
    - name: logging-operator
      image: ghcr.io/kube-logging/logging-operator:4.2.0
    - name: config-reloader
      image: ghcr.io/kube-logging/config-reloader:v0.0.5
    - name: node-exporter
      image: ghcr.io/kube-logging/node-exporter:v0.6.1
    - name: syslog-ng-exporter
      image: ghcr.io/kube-logging/syslog-ng-exporter:v0.0.16
    - name: syslogng-reload
      image: ghcr.io/kube-logging/syslogng-reload:v1.3.1
