apiVersion: logging.banzaicloud.com/v1alpha2
kind: Logging
metadata:
  name: {{ include "nginx-logging-loki-demo.fullname" . }}-logging
spec:
  fluentd: {}
  fluentbit: {}
  controlNamespace: {{ .Release.Namespace }}
