apiVersion: logging.banzaicloud.com/v1alpha1
kind: Fluentbit
metadata:
  name: example-fluentbit
  labels:
    release: test
spec:
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path:   "/api/v1/metrics/prometheus"
    prometheus.io/port:   "2020"
  tls:
    enabled: false
  image:
    tag: "1.1.3"
    repository: "fluent/fluent-bit"
    pullPolicy: "IfNotPresent"
  resources: {}
