apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: logging-operator
  template:
    metadata:
      labels:
        name: logging-operator
    spec:
      serviceAccountName: logging-operator
      containers:
        - name: logging-operator
          # Replace this with the built image name
          image: banzaicloud/logging-operator:1.0.0
          command:
          - logging-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "logging-operator"
