kind: ConfigMap
apiVersion: v1
metadata:
  name: "logging-operator-config"
  labels:
    app:  "logging-operator"
data:
  config.toml: |-
    # This is the example config for the logging operator

    [logging-operator]
    rbac = false
    namespace = "default"

    [fluent-bit]
    enabled = true
    namespace = "default"
    tls_enabled = true
    config ="""[SERVICE]
       Flush        1
       Daemon       Off
       Log_Level    info
       Parsers_File parsers.conf
       HTTP_Server  On
       HTTP_Listen  0.0.0.0
       HTTP_Port    {{ .Monitor.Port }}

    [INPUT]
       Name             tail
       Path             /var/log/containers/*.log
       Parser           docker
       Tag              kubernetes.*
       Refresh_Interval 5
       Mem_Buf_Limit    5MB
       Skip_Long_Lines  On
       DB               /tail-db/tail-containers-state.db
       DB.Sync          Normal

    [FILTER]
       Name                kubernetes
       Match               kubernetes.*
       Kube_URL            https://kubernetes.default.svc:443
       Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
       Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
       Merge_Log           On

    [OUTPUT]
       Name          forward
       Match         *
       Host          fluentd.default.svc
       Port          24240
       {{ if .TLS.Enabled }}
       tls           On
       tls.verify    Off
       tls.ca_file   /fluent-bit/tls/caCert
       tls.crt_file  /fluent-bit/tls/clientCert
       tls.key_file  /fluent-bit/tls/clientKey
       Shared_Key    {{ .TLS.SharedKey }}
       {{- end }}
       Retry_Limit   False"""

    [fluentd]
    enabled = true
    namespace = "default"
    tls_enabled = true
    default = """
            # include other config files
            @include /fluentd/etc/input.conf
            @include /fluentd/etc/app_config/*
            @include /fluentd/etc/devnull.conf"""
    input = """
            # Enable RPC endpoint (this allows to trigger config reload without restart)
            <system>
              rpc_endpoint 127.0.0.1:24444
            </system>
            # Prometheus monitoring
            <source>
                @type prometheus
            </source>
            <source>
                @type prometheus_monitor
            </source>
            <source>
                @type prometheus_output_monitor
            </source>

            # Input plugin
            <source>
                @type   forward
                port    24240
                @log_level debug
                {{ if .TLS.Enabled }}
                <security>
                  self_hostname fluentd
                  shared_key {{ .TLS.SharedKey }}
                </security>
                <transport tls>
                  version                TLSv1_2
                  ca_path                /fluentd/etc/tls/caCert
                  cert_path              /fluentd/etc/tls/serverCert
                  private_key_path       /fluentd/etc/tls/serverKey
                  client_cert_auth       true
                </transport>
                {{- end }}
            </source>

            # Prevent fluentd from handling records containing its own logs. Otherwise
            # it can lead to an infinite loop, when error in sending one message generates
            # another message which also fails to be sent and so on.
            <match **.fluentd**>
                @type null
            </match>

            <match **.fluent-bit**>
                @type null
            </match>

            <match kubernetes.**>
              @type rewrite_tag_filter
              <rule>
                key $.kubernetes.namespace_name
                pattern ^(.+)$
                tag $1.${tag_parts[0]}
              </rule>
            </match>

            <match *.kubernetes.**>
              @type rewrite_tag_filter
              <rule>
                key $.kubernetes.labels.app
                pattern ^(.+)$
                tag $1.${tag_parts[0]}.${tag_parts[1]}
              </rule>
            </match>"""
    devnull ="""
            <match **>
                @type null
            </match>"""