apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    tenant: infra
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Tenant
metadata:
  name: infra
  labels:
    collector: cluster
spec:
  logSourceNamespaceSelectors:
    - matchLabels:
        tenant: customer-a
    - matchLabels:
        tenant: customer-b
  subscriptionNamespaceSelectors:
    - matchLabels:
        tenant: infra
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Subscription
metadata:
  name: infra
  namespace: infra
  labels:
    tenant: infra
spec:
  condition: "true"
  outputs:
    - name: infra-all
      namespace: infra
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Output
metadata:
  name: infra-all
  namespace: infra
spec:
  otlp:
    endpoint: receiver-infra-collector.infra.svc.cluster.local:4317
    tls:
      insecure: true
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: receiver-infra
  namespace: infra
spec:
  managementState: managed
  config: |
    receivers:
      otlp:
        protocols:
          grpc:

    exporters:
      debug:
        verbosity: detailed
    service:
        pipelines:
          logs:
            receivers: [otlp]
            exporters: [debug]
