apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: defaultlogging
spec:
  fluentd:
    logLevel: debug
    disablePvc: true
  fluentbit:
    image:
      tag: 1.6.8-debug
      repository: fluent/fluent-bit
      pullPolicy: IfNotPresent
  controlNamespace: default
