---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.3
  name: syslogngclusterflows.logging.banzaicloud.io
spec:
  group: logging.banzaicloud.io
  names:
    categories:
    - logging-all
    kind: SyslogNGClusterFlow
    listKind: SyslogNGClusterFlowList
    plural: syslogngclusterflows
    singular: syslogngclusterflow
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Is the flow active?
      jsonPath: .status.active
      name: Active
      type: boolean
    - description: Number of problems
      jsonPath: .status.problemsCount
      name: Problems
      type: integer
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              filters:
                items:
                  properties:
                    id:
                      type: string
                    match:
                      properties:
                        and:
                          x-kubernetes-preserve-unknown-fields: true
                        not:
                          x-kubernetes-preserve-unknown-fields: true
                        or:
                          x-kubernetes-preserve-unknown-fields: true
                        regexp:
                          properties:
                            flags:
                              items:
                                type: string
                              type: array
                            pattern:
                              type: string
                            template:
                              type: string
                            type:
                              type: string
                            value:
                              type: string
                          required:
                          - pattern
                          type: object
                      type: object
                    parser:
                      properties:
                        metrics-probe:
                          properties:
                            key:
                              type: string
                            labels:
                              additionalProperties:
                                type: string
                              type: object
                            level:
                              type: integer
                          type: object
                        regexp:
                          properties:
                            flags:
                              items:
                                type: string
                              type: array
                            patterns:
                              items:
                                type: string
                              type: array
                            prefix:
                              type: string
                            template:
                              type: string
                          required:
                          - patterns
                          type: object
                        syslog-parser:
                          properties:
                            flags:
                              items:
                                type: string
                              type: array
                          type: object
                      type: object
                    rewrite:
                      items:
                        properties:
                          group_unset:
                            properties:
                              condition:
                                properties:
                                  and:
                                    x-kubernetes-preserve-unknown-fields: true
                                  not:
                                    x-kubernetes-preserve-unknown-fields: true
                                  or:
                                    x-kubernetes-preserve-unknown-fields: true
                                  regexp:
                                    properties:
                                      flags:
                                        items:
                                          type: string
                                        type: array
                                      pattern:
                                        type: string
                                      template:
                                        type: string
                                      type:
                                        type: string
                                      value:
                                        type: string
                                    required:
                                    - pattern
                                    type: object
                                type: object
                              pattern:
                                type: string
                            required:
                            - pattern
                            type: object
                          rename:
                            properties:
                              condition:
                                properties:
                                  and:
                                    x-kubernetes-preserve-unknown-fields: true
                                  not:
                                    x-kubernetes-preserve-unknown-fields: true
                                  or:
                                    x-kubernetes-preserve-unknown-fields: true
                                  regexp:
                                    properties:
                                      flags:
                                        items:
                                          type: string
                                        type: array
                                      pattern:
                                        type: string
                                      template:
                                        type: string
                                      type:
                                        type: string
                                      value:
                                        type: string
                                    required:
                                    - pattern
                                    type: object
                                type: object
                              newName:
                                type: string
                              oldName:
                                type: string
                            required:
                            - newName
                            - oldName
                            type: object
                          set:
                            properties:
                              condition:
                                properties:
                                  and:
                                    x-kubernetes-preserve-unknown-fields: true
                                  not:
                                    x-kubernetes-preserve-unknown-fields: true
                                  or:
                                    x-kubernetes-preserve-unknown-fields: true
                                  regexp:
                                    properties:
                                      flags:
                                        items:
                                          type: string
                                        type: array
                                      pattern:
                                        type: string
                                      template:
                                        type: string
                                      type:
                                        type: string
                                      value:
                                        type: string
                                    required:
                                    - pattern
                                    type: object
                                type: object
                              field:
                                type: string
                              value:
                                type: string
                            required:
                            - field
                            - value
                            type: object
                          subst:
                            properties:
                              condition:
                                properties:
                                  and:
                                    x-kubernetes-preserve-unknown-fields: true
                                  not:
                                    x-kubernetes-preserve-unknown-fields: true
                                  or:
                                    x-kubernetes-preserve-unknown-fields: true
                                  regexp:
                                    properties:
                                      flags:
                                        items:
                                          type: string
                                        type: array
                                      pattern:
                                        type: string
                                      template:
                                        type: string
                                      type:
                                        type: string
                                      value:
                                        type: string
                                    required:
                                    - pattern
                                    type: object
                                type: object
                              field:
                                type: string
                              flags:
                                items:
                                  type: string
                                type: array
                              pattern:
                                type: string
                              replace:
                                type: string
                              type:
                                type: string
                            required:
                            - field
                            - pattern
                            - replace
                            type: object
                          unset:
                            properties:
                              condition:
                                properties:
                                  and:
                                    x-kubernetes-preserve-unknown-fields: true
                                  not:
                                    x-kubernetes-preserve-unknown-fields: true
                                  or:
                                    x-kubernetes-preserve-unknown-fields: true
                                  regexp:
                                    properties:
                                      flags:
                                        items:
                                          type: string
                                        type: array
                                      pattern:
                                        type: string
                                      template:
                                        type: string
                                      type:
                                        type: string
                                      value:
                                        type: string
                                    required:
                                    - pattern
                                    type: object
                                type: object
                              field:
                                type: string
                            required:
                            - field
                            type: object
                        type: object
                      type: array
                  type: object
                type: array
              globalOutputRefs:
                items:
                  type: string
                type: array
              loggingRef:
                type: string
              match:
                properties:
                  and:
                    x-kubernetes-preserve-unknown-fields: true
                  not:
                    x-kubernetes-preserve-unknown-fields: true
                  or:
                    x-kubernetes-preserve-unknown-fields: true
                  regexp:
                    properties:
                      flags:
                        items:
                          type: string
                        type: array
                      pattern:
                        type: string
                      template:
                        type: string
                      type:
                        type: string
                      value:
                        type: string
                    required:
                    - pattern
                    type: object
                type: object
              outputMetrics:
                items:
                  properties:
                    key:
                      type: string
                    labels:
                      additionalProperties:
                        type: string
                      type: object
                    level:
                      type: integer
                  type: object
                type: array
            type: object
          status:
            properties:
              active:
                type: boolean
              problems:
                items:
                  type: string
                type: array
              problemsCount:
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
