apiVersion: v1
description: Logging operator CR for Fluentd and Fluent-bit.
name: logging-operator-fluent
version: 0.1.3
home: https://github.com/banzaicloud/logging-operator
icon: https://banzaicloud.com/img/banzai-cloud-logo.png
keywords:
  - logging
  - monitoring
  - fluentd
  - fluenbit
  - operator
sources:
  - https://github.com/banzaicloud/logging-operator
maintainers:
  - name: Banzai Cloud
    email: info@banzaicloud.com

