apiVersion: v1
appVersion: "3.8.3"
description: A Helm chart for Kubernetes
name: logging-demo
version: 3.8.3
icon: https://raw.githubusercontent.com/banzaicloud/logging-operator/master/docs/img/icon.png
